base:
  model_arc: "Bert"
  model_name: "bert-base-multilingual-cased"
  seed: 42
  train_args:
    num_workers: 5
    num_epochs: 15
    train_batch_size: 16
    eval_batch_size: 32
    lr: 0.00005
    output_dir: './results/base'
  val_args:
    use_kfold: True
    num_k: 5
    test_size: 0.2

electra-base-v3:
  model_arc: "Electra"
  model_name: "monologg/koelectra-base-v3-discriminator"
  seed: 42
  train_args:
    num_workers: 5
    num_epochs: 15
    train_batch_size: 16
    eval_batch_size: 32
    lr: 0.00005
    output_dir: './results/electra-base-v3'
  val_args:
    use_kfold: True
    num_k: 5
    test_size: 0

xlm-roberta-base:
  model_arc: "roberta"
  model_name: "xlm-roberta-large"
  seed: 42
  train_args:
    num_workers: 5
    num_epochs: 15
    train_batch_size: 16
    eval_batch_size: 32
    lr: 0.00005
    output_dir: './results/xlm-roberta-large'
  val_args:
    use_kfold: True
    num_k: 5
    test_size: 0

